# Site
title:              nithithecrazycoder
bio:                'Nithyanantham, He is hardcore programmer having more than 5 years experience in various microsoft and open source technologies such as WCF, ASP.NET MVC, WEB API, AZURE, Angular and etc.'
description:        "Nithyanantham S"
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://nithyanantham.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   nithyanantham

# Social
# if you don't have any of social below, comment the line.
google:
  plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email: nithyananthamn@gmail.com
twitter:            nithyananthams
facebook:           https://www.facebook.com/nithyananthamn
github-url:         https://github.com/nithyanantham
stackoverflow:     2140399/nithyanantham   from a "http://stackoverflow.com/users/2140399/nithyanantham" link
linkedin:          https://in.linkedin.com/in/nithyanantham-s-0b644222
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
